### ISSUE TITLE
Skeleton function

### ISSUE THREAD

**Issue by don-mums** [woodgern/confusables#23]
Hi!
There used to be confusables for python that I forked and no longer exists. It had one very useful function `skeleton()`. It returned string that transformed all confusables to normalized values. So you could detect that original strings don't match but normalized strings match. Like `A` in latin and `А` in azbuka.

https://github.com/don-mums/confusables/blob/master/confusables.py

Is this something you would like to include into your project? The only thing I found that remotely resembles `skeleton()` is `_asciify()` but this also removes all non ascii characters, which is not very useful for us. As you can see on the example below.

    'Veľký Krtíš'.encode('ascii', 'ignore').decode('ascii') == 'Vek Krt'

**Comment by TrustedMercury** [comment]
Is `normalize` what you're referring to? 

https://github.com/woodgern/confusables/blob/master/confusables/__init__.py#L54-L79

**Comment by woodgern** [comment]
@don-mums `normalize` is intended to provide that behaviour

**Comment by stdedos** [comment]
Maybe OP is talking about https://gitlab.com/dirn/flake8-confusables?

In my case, line https://gitlab.com/dirn/flake8-confusables/-/blob/master/flake8_confusables.py#L39 blows up, and the [flake8-confusables](https://gitlab.com/dirn/flake8-confusables) developer hasn't specified a `confusables` version (https://gitlab.com/dirn/flake8-confusables/-/blob/master/setup.py#L33)

**Comment by don-mums** [comment]
Sorry I've lost all context from this issue. I don't work for the company where we needed this. I even switched Python for Elixir. I don't care. I'm closing this so nobody is wasting time looking into this when i apparently has solution.
