### ISSUE TITLE
confusables.txt is outdated

### ISSUE THREAD

**Issue by tomaszn** [woodgern/confusables#24]
The latest one at the moment is [version 13.0.0](https://www.unicode.org/Public/security/13.0.0/confusables.txt). Could be updated also in README.md.

**Comment by woodgern** [comment]
Hi! A whole year too late, but I've updated to `13.0.0`, which seems to still be the latest version. I've also updated the README here (https://github.com/woodgern/confusables#updating-to-the-latest-unicode-confusables-version) to provide instructions for any kind citizens that want to update it themself :) Thanks for the nudge!
